import styles from "../styles/eventsAndProgram.module.css"
import {Text} from "@nextui-org/react";
import Timeline2 from "../components/Timeline2";

export default function EventsAndProgram(){
    return(
        <>
            <div className={styles.main}>
                <Text h1 className={styles.heading}>
                    Events and Programs
                </Text>
                <Text h1 className={styles.heading2}>
                    Supercharger
                </Text>
                <Text className={styles.heroText}>
                    If you are a working professional with a passion for
                    working with startups in your spare time, this is the
                    best forum for you. There are 3 roles which you can
                    register as:
                </Text>
                <Timeline2></Timeline2>
                <Text weight={'thin'} size={18} className={styles.belowTimeline}>
                    We will be taking 5% equity in return for the above services and will put in an investment of INR 60000 to the startup.
                </Text>
                <Text h1 className={styles.heading2}>
                    Epsilon
                </Text>
                <div style={{ height: "4vh" }}></div>
                <Text css={{padding:"0 5vw"}} h2 i weight={'bold'} className={styles.heading4}>
                    The Reciprocal Pitch Contest
                </Text>
                <Text className={styles.heroText}>
                    Epsilon is one of its kind event which aims at identifying extraordinary college students to transform great ideas into million-dollar businesses.
                </Text>
                <div style={{ height: "10vh" }}></div>
                <Text
                    h1
                    size={28}
                    weight={'medium'}
                >How this works</Text>
                <div className={styles.list}>
                    <ul>
                        <li>1.  The Reciprocal Pitch will start with 5 ideas for which we will be searching for the
                            right team.

                            <ul>
                                <li>
                                    a. 3 of these ideas have been generated by us.
                                </li>
                                <li>
                                    b. 2 will be selected from the ones submitted by experienced professionals from industry. (Pioneers)
                                </li>
                            </ul>
                        </li>
                        <li>
                            2. All ideas will have a seed funding of 50000 100000 INR.
                        </li>
                        <li>
                            3. Students will apply and chose an idea from any of these 5 and pitch
                            themselves for being the part of the founding team.
                        </li>
                        <li>
                            4. Each student will be interviewed by us or the Pioneer and he/she/us will select
                            the right team.
                        </li>
                        <li>
                            5. The team along with the idea will be registered as a Pvt. Ltd. Company.
                        </li>
                        <li>
                            6. Using the SF strategy planning tool, the team will be given a strategy and a set
                            of goals to achieve. They will work on these goals to build their startup
                        </li>
                    </ul>
                </div>
            </div>
            <div style={{ height: "10vh" }}></div>
        </>
    )
}